export const industry = [
  { title: "農業，林業" },
  { title: "漁業" },
  { title: "鉱業，採石業，砂利採取業" },
  { title: "建設業" },
  { title: "製造業" },
  { title: "電気・ガス・熱供給・水道業" },
  { title: "情報通信業" },
  { title: "運輸業，郵便業" },
  { title: "卸売業・小売業" },
  { title: "金融業・保険業" },
  { title: "不動産業，物品賃貸業" },
  { title: "学術研究，専門・技術サービス業" },
  { title: "宿泊業，飲食サービス業" },
  { title: "生活関連サービス業，娯楽業" },
  { title: "教育，学習支援業" },
  { title: "医療，福祉" },
  { title: "複合サービス事業" },
  { title: "サービス業（他に分類されないもの）" },
  { title: "公務（他に分類されるものを除く）" },
  { title: "分類不能の産業" },
];

export const occupation = [
  { title: "事務・管理系" },
  { title: "企画・マーケティング系" },
  { title: "営業系" },
  { title: "技術・研究系" },
  { title: "販売・サービス系" },
  { title: "専門系" },
  { title: "医療・福祉系" },
  { title: "金融系" },
  { title: "クリエイティブ系" },
  { title: "IT系" },
  { title: "教育・保育・公共サービス系" },
];
