//業種
export const industry = [
  { value: "農業，林業", label: "農業，林業" },
  { value: "漁業", label: "漁業" },
  { value: "鉱業，採石業，砂利採取業", label: "鉱業，採石業，砂利採取業" },
  { value: "建設業", label: "建設業" },
  { value: "製造業", label: "製造業" },
  { value: "電気・ガス・熱供給・水道業", label: "電気・ガス・熱供給・水道業" },
  { value: "情報通信業", label: "情報通信業" },
  { value: "運輸業，郵便業", label: "運輸業，郵便業" },
  { value: "卸売業・小売業", label: "卸売業・小売業" },
  { value: "金融業・保険業", label: "金融業・保険業" },
  { value: "不動産業，物品賃貸業", label: "不動産業，物品賃貸業" },
  {
    value: "学術研究，専門・技術サービス業",
    label: "学術研究，専門・技術サービス業",
  },
  { value: "宿泊業，飲食サービス業", label: "宿泊業，飲食サービス業" },
  { value: "生活関連サービス業，娯楽業", label: "生活関連サービス業，娯楽業" },
  { value: "教育，学習支援業", label: "教育，学習支援業" },
  { value: "医療，福祉", label: "医療，福祉" },
  { value: "複合サービス事業", label: "複合サービス事業" },
  {
    value: "サービス業（他に分類されないもの）",
    label: "サービス業（他に分類されないもの）",
  },
  {
    value: "公務（他に分類されるものを除く）",
    label: "公務（他に分類されるものを除く）",
  },
  { value: "分類不能の産業", label: "分類不能の産業" },
];

//職種
export const occupation = [
  { value: "事務・管理系", label: "事務・管理系" },
  { value: "企画・マーケティング系", label: "企画・マーケティング系" },
  { value: "営業系", label: "営業系" },
  { value: "技術・研究系", label: "技術・研究系" },
  { value: "販売・サービス系", label: "販売・サービス系" },
  { value: "専門系", label: "専門系" },
  { value: "医療・福祉系", label: "医療・福祉系" },
  { value: "金融系", label: "金融系" },
  { value: "クリエイティブ系", label: "クリエイティブ系" },
  { value: "IT系", label: "IT系" },
  { value: "教育・保育・公共サービス系", label: "教育・保育・公共サービス系" },
];

export const area = [
  { title: "名古屋市" },
  { title: "豊橋市" },
  { title: "岡崎市" },
  { title: "一宮市" },
  { title: "春日井市" },
  { title: "豊川市" },
  { title: "津島市" },
  { title: "碧南市" },
  { title: "刈谷市" },
  { title: "豊田市" },
  { title: "安城市" },
  { title: "西尾市" },
  { title: "犬山市" },
  { title: "江南市" },
  { title: "小牧市" },
  { title: "稲沢市" },
  { title: "東海市" },
  { title: "知立市" },
  { title: "尾張旭市" },
  { title: "高浜市" },
  { title: "豊明市" },
  { title: "日進市" },
  { title: "みよし市" },
  { title: "あま市" },
  { title: "西春日井郡" },
  { title: "丹羽郡" },
  { title: "海部郡" },
  { title: "岐阜市" },
  { title: "大垣市" },
  { title: "美濃市" },
  { title: "美濃加茂市" },
  { title: "各務原市" },
  { title: "可児市" },
  { title: "飛騨市" },
  { title: "加茂郡" },
  { title: "津市" },
  { title: "四日市市" },
  { title: "松阪市" },
  { title: "桑名市" },
  { title: "鈴鹿市" },
  { title: "三重郡" },
  { title: "員弁郡" },
  { title: "仙台市" },
  { title: "埼玉県" },
  { title: "東京都" },
  { title: "横浜市" },
  { title: "厚木市" },
  { title: "浜松市" },
  { title: "静岡市" },
  { title: "大阪市" },
  { title: "神戸市" },
  { title: "福井市" },
];

//必須資格
export const qualification = [
  { title: "不問" },
  { title: "普通自動車免許（AT限定可）" },
  { title: "普通自動車免許" },
  { title: "準中型自動車免許" },
  { title: "第一種電気工事士" },
  { title: "第二種電気工事士" },
  { title: "電気主任技術者第3種" },
  { title: "第1級陸上特殊無線技士" },
  { title: "工事担任者AD･DD総合種" },
  { title: "基本情報技術者" },
];

//求める人物像
export const person = [
  "真面目",
  "コミュニケーション能力",
  "誠実",
  "素直",
  "チームワーク",
  "責任感",
  "柔軟性",
  "リーダーシップ",
  "自己管理",
  "創造力",
  "向上心",
  "課題解決力",
];
