export const selectBox2 = [
  { label: "北海道", value: "北海道" },
  { label: "青森県", value: "青森県" },
  { label: "岩手県", value: "岩手県" },
  { label: "宮城県", value: "宮城県" },
  { label: "秋田県", value: "秋田県" },
  { label: "山形県", value: "山形県" },
  { label: "福島県", value: "福島県" },
  { label: "茨城県", value: "茨城県" },
  { label: "栃木県", value: "栃木県" },
  { label: "群馬県", value: "群馬県" },
  { label: "埼玉県", value: "埼玉県" },
  { label: "千葉県", value: "千葉県" },
  { label: "東京都", value: "東京都" },
  { label: "神奈川県", value: "神奈川県" },
  { label: "新潟県", value: "新潟県" },
  { label: "富山県", value: "富山県" },
  { label: "石川県", value: "石川県" },
  { label: "福井県", value: "福井県" },
  { label: "山梨県", value: "山梨県" },
  { label: "長野県", value: "長野県" },
  { label: "岐阜県", value: "岐阜県" },
  { label: "静岡県", value: "静岡県" },
  { label: "愛知県", value: "愛知県" },
  { label: "三重県", value: "三重県" },
  { label: "滋賀県", value: "滋賀県" },
  { label: "京都府", value: "京都府" },
  { label: "大阪府", value: "大阪府" },
  { label: "兵庫県", value: "兵庫県" },
  { label: "奈良県", value: "奈良県" },
  { label: "和歌山県", value: "和歌山県" },
  { label: "鳥取県", value: "鳥取県" },
  { label: "島根県", value: "島根県" },
  { label: "岡山県", value: "岡山県" },
  { label: "広島県", value: "広島県" },
  { label: "山口県", value: "山口県" },
  { label: "徳島県", value: "徳島県" },
  { label: "香川県", value: "香川県" },
  { label: "愛媛県", value: "愛媛県" },
  { label: "高知県", value: "高知県" },
  { label: "福岡県", value: "福岡県" },
  { label: "佐賀県", value: "佐賀県" },
  { label: "長崎県", value: "長崎県" },
  { label: "熊本県", value: "熊本県" },
  { label: "大分県", value: "大分県" },
  { label: "宮崎県", value: "宮崎県" },
  { label: "鹿児島県", value: "鹿児島県" },
  { label: "沖縄県", value: "沖縄県" },
];

export const options = [
  { title: "ITパスポート" },
  { title: "情報セキュリティマネジメント" },
  { title: "基本情報技術者" },
  { title: "応用情報技術者" },
  { title: "ITストラテジスト" },
  { title: "システムアーキテクト" },
  { title: "プロジェクトマネージャ" },
  { title: "ネットワークスペシャリスト" },
  { title: "データベーススペシャリスト" },
  { title: "エンベデッドシステムスペシャリスト" },
  { title: "ITサービスマネージャ" },
  { title: "システム監査技術者" },
  { title: "情報処理安全確保支援士" },
];

export const selectBox = [
  { label: "情報総合学科", value: "情報総合学科" },
  { label: "情報システム科", value: "情報システム科" },
  { label: "情報処理学科", value: "情報処理学科" },
  {
    label: "AIイノベーション学科 AIシステムコース",
    value: "AIイノベーション学科 AIシステムコース",
  },
  {
    label: "AIイノベーション学科 グローバルコミュニケーションコース",
    value: "AIイノベーション学科 グローバルコミュニケーションコース",
  },
  { label: "高度情報学科", value: "高度情報学科" },
  {
    label: "ゲーム総合学科 ゲームプログラミングコース",
    value: "ゲーム総合学科 ゲームプログラミングコース",
  },
  {
    label: "ゲーム総合学科 ゲームCGコース",
    value: "ゲーム総合学科 ゲームCGコース",
  },
  { label: "ゲームサイエンス学科", value: "ゲームサイエンス学科" },
  { label: "ゲームCG学科", value: "ゲームCG学科" },
  {
    label: "ゲーム研究科 ゲームプログラミングコース",
    value: "ゲーム研究科 ゲームプログラミングコース",
  },
  {
    label: "ゲーム研究科 ゲームCGコース",
    value: "ゲーム研究科 ゲームCGコース",
  },
  { label: "映像メディア科", value: "映像メディア科" },
  { label: "映像音響科 映像コース", value: "映像音響科 映像コース" },
  {
    label: "映像音響科 音響・照明コース",
    value: "映像音響科 音響・照明コース",
  },
  { label: "映像メディア研究科", value: "映像メディア研究科" },
  { label: "電気工学科", value: "電気工学科" },
  { label: "電業技術学科", value: "電業技術学科" },
  { label: "電気工学研究科", value: "電気工学研究科" },
  { label: "電子情報学科", value: "電子情報学科" },
  { label: "電子情報研究科", value: "電子情報研究科" },
  { label: "機械工学科", value: "機械工学科" },
  { label: "機械CAD設計科", value: "機械CAD設計科" },
  { label: "産業技術研究科", value: "産業技術研究科" },
];

export const selectBox1 = [
  { label: "25卒", value: "25卒" },
  { label: "26卒", value: "26卒" },
  { label: "27卒", value: "27卒" },
  { label: "28卒", value: "28卒" },
  { label: "29卒", value: "29卒" },
  { label: "30卒", value: "30卒" },
  { label: "31卒", value: "31卒" },
  { label: "32卒", value: "32卒" },
  { label: "33卒", value: "33卒" },
  { label: "34卒", value: "34卒" },
  { label: "35卒", value: "35卒" },
  { label: "36卒", value: "36卒" },
];

export const selectBox3 = [
  { label: "男", value: "男" },
  { label: "女", value: "女" },
];
