//居住地域
export const selectBox2 = [
  { label: "北海道", value: "北海道" },
  { label: "青森県", value: "青森県" },
  { label: "岩手県", value: "岩手県" },
  { label: "宮城県", value: "宮城県" },
  { label: "秋田県", value: "秋田県" },
  { label: "山形県", value: "山形県" },
  { label: "福島県", value: "福島県" },
  { label: "茨城県", value: "茨城県" },
  { label: "栃木県", value: "栃木県" },
  { label: "群馬県", value: "群馬県" },
  { label: "埼玉県", value: "埼玉県" },
  { label: "千葉県", value: "千葉県" },
  { label: "東京都", value: "東京都" },
  { label: "神奈川県", value: "神奈川県" },
  { label: "新潟県", value: "新潟県" },
  { label: "富山県", value: "富山県" },
  { label: "石川県", value: "石川県" },
  { label: "福井県", value: "福井県" },
  { label: "山梨県", value: "山梨県" },
  { label: "長野県", value: "長野県" },
  { label: "岐阜県", value: "岐阜県" },
  { label: "静岡県", value: "静岡県" },
  { label: "愛知県", value: "愛知県" },
  { label: "三重県", value: "三重県" },
  { label: "滋賀県", value: "滋賀県" },
  { label: "京都府", value: "京都府" },
  { label: "大阪府", value: "大阪府" },
  { label: "兵庫県", value: "兵庫県" },
  { label: "奈良県", value: "奈良県" },
  { label: "和歌山県", value: "和歌山県" },
  { label: "鳥取県", value: "鳥取県" },
  { label: "島根県", value: "島根県" },
  { label: "岡山県", value: "岡山県" },
  { label: "広島県", value: "広島県" },
  { label: "山口県", value: "山口県" },
  { label: "徳島県", value: "徳島県" },
  { label: "香川県", value: "香川県" },
  { label: "愛媛県", value: "愛媛県" },
  { label: "高知県", value: "高知県" },
  { label: "福岡県", value: "福岡県" },
  { label: "佐賀県", value: "佐賀県" },
  { label: "長崎県", value: "長崎県" },
  { label: "熊本県", value: "熊本県" },
  { label: "大分県", value: "大分県" },
  { label: "宮崎県", value: "宮崎県" },
  { label: "鹿児島県", value: "鹿児島県" },
  { label: "沖縄県", value: "沖縄県" },
];
//保有資格
export const options = [
  { title: "無し", id: 0 },
  { title: "ITパスポート", id: 1 },
  { title: "情報セキュリティマネジメント", id: 2 },
  { title: "基本情報技術者", id: 3 },
  { title: "応用情報技術者", id: 4 },
  { title: "ITストラテジスト", id: 5 },
  { title: "システムアーキテクト", id: 6 },
  { title: "プロジェクトマネージャ", id: 7 },
  { title: "ネットワークスペシャリスト", id: 8 },
  { title: "データベーススペシャリスト", id: 9 },
  { title: "エンベデッドシステムスペシャリスト", id: 10 },
  { title: "ITサービスマネージャ", id: 11 },
  { title: "システム監査技術者", id: 12 },
  { title: "情報処理安全確保支援士", id: 13 },
  { title: "普通自動車第一種運転免許", id: 14 },
  { title: "普通自動車第一種運転免許（AT限定）", id: 15 },
  { title: "日商簿記3級", id: 16 },
  { title: "日商簿記2級", id: 17 },
  { title: "日商簿記1級", id: 18 },
  { title: "ORACLE MASTER Bronze DBA", id: 19 },
  { title: "ORACLE MASTER Silver DBA", id: 20 },
  { title: "ORACLE MASTER Gold DBA", id: 21 },
  { title: "ORACLE MASTER Platinum DBA", id: 22 },
  { title: "ORACLE MASTER Silver SQL", id: 23 },
  { title: "LinuCレベル1", id: 24 },
  { title: "LinuCレベル2", id: 25 },
  { title: "LinuCレベル3", id: 26 },
  { title: "LinuCシステムアーキテクト", id: 27 },
  { title: "Oracle Certified Java Programmer, Bronze SE", id: 28 },
  { title: "Oracle Certified Java Programmer, Silver SE 11", id: 29 },
  { title: "Oracle Certified Java Programmer, Gold SE 11", id: 30 },
]; //id0で選択できないようにできる
//学科
export const selectBox = [
  { label: "情報総合学科", value: [1, "情報総合学科"] },
  { label: "情報システム科", value: [2, "情報システム科"] },
  { label: "情報処理学科", value: [3, "情報処理学科"] },
  {
    label: "AIイノベーション学科 AIシステムコース",
    value: [4, "AIイノベーション学科 AIシステムコース"],
  },
  {
    label: "AIイノベーション学科 グローバルコミュニケーションコース",
    value: [5, "AIイノベーション学科 グローバルコミュニケーションコース"],
  },
  { label: "高度情報学科", value: [6, "高度情報学科"] },
  {
    label: "ゲーム総合学科 ゲームプログラミングコース",
    value: [7, "ゲーム総合学科 ゲームプログラミングコース"],
  },
  {
    label: "ゲーム総合学科 ゲームCGコース",
    value: [8, "ゲーム総合学科 ゲームCGコース"],
  },
  { label: "ゲームサイエンス学科", value: [9, "ゲームサイエンス学科"] },
  { label: "ゲームCG学科", value: [10, "ゲームCG学科"] },
  {
    label: "ゲーム研究科 ゲームプログラミングコース",
    value: [11, "ゲーム研究科 ゲームプログラミングコース"],
  },
  {
    label: "ゲーム研究科 ゲームCGコース",
    value: [12, "ゲーム研究科 ゲームCGコース"],
  },
  { label: "映像メディア科", value: [13, "映像メディア科"] },
  { label: "映像音響科 映像コース", value: [14, "映像音響科 映像コース"] },
  {
    label: "映像音響科 音響・照明コース",
    value: [15, "映像音響科 音響・照明コース"],
  },
  { label: "映像メディア研究科", value: [16, "映像メディア研究科"] },
  { label: "電気工学科", value: [17, "電気工学科"] },
  { label: "電業技術学科", value: [18, "電業技術学科"] },
  { label: "電気工学研究科", value: [19, "電気工学研究科"] },
  { label: "電子情報学科", value: [20, "電子情報学科"] },
  { label: "電子情報研究科", value: [21, "電子情報研究科"] },
  { label: "機械工学科", value: [22, "機械工学科"] },
  { label: "機械CAD設計科", value: [23, "機械CAD設計科"] },
  { label: "産業技術研究科", value: [24, "産業技術研究科"] },
];

//卒業年
export const selectBox1 = [
  { label: "25卒", value: "2025" },
  { label: "26卒", value: "2026" },
  { label: "27卒", value: "2027" },
  { label: "28卒", value: "2028" },
  { label: "29卒", value: "2029" },
  { label: "30卒", value: "2030" },
  { label: "31卒", value: "2031" },
  { label: "32卒", value: "2032" },
  { label: "33卒", value: "2033" },
  { label: "34卒", value: "2034" },
  { label: "35卒", value: "2035" },
  { label: "36卒", value: "2036" },
];
