name: Deploy Function to Azure VM

on:
  push:
    branches:
      - main-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_BACKENDPRIVATE_KEY }}

      - name: Copy function directory to Azure VM
        run: |
          rsync -avz --delete ./function/ user@your-azure-vm-ip:/path/to/remote/function/

      - name: Restart function service
        run: |
          ssh user@your-azure-vm-ip 'sudo systemctl restart your-function-service'
