name: Deploy to Azure VM

on:
  push:
    branches:
      - main-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_BACKENDPRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_BACKENDIP }} << 'EOF'
            cd etc/CVAISotuken
            git switch main-backend
            git pull origin main-backend
            npm install  # or any other build steps
          EOF
