name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Azure VM
        run: |
          VM_USER="azureuser"
          BUILD_DIR="dist"  # 成果物が生成されるディレクトリ

          # ダウンロードしたビルドアーティファクトをVMに転送
          echo "$SSH_PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
          scp -i id_rsa -r $BUILD_DIR $VM_USER@$VM_IP:/home/azureuser/

          # SSHキーをクリーンアップ
          rm id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
          VM_IP: ${{ secrets.AZURE_VM_IP }}
