name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (or your build tool)
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploy to Azure VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}
        run: |
          # Define variables
          VM_USER="azureuser"
          VM_IP= ${{ secrets.AZURE_VM_IP }}
          BUILD_DIR="./build"

          # Install SSH client if not already available
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # SCP to Azure VM
          scp -i $SSH_PRIVATE_KEY -r $BUILD_DIR $VM_USER@$VM_IP:/path/
